# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-13 19:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doacoes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cidade',
            old_name='codigoIbge',
            new_name='codigoibge',
        ),
    ]
